config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    },
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'apply',
      edit: 'settings',
      password: 'forgot'
    }

  root 'pages#index'

  get 'hackweek' => 'pages#hackweek', as: :hackweek

  get 'application' => 'users#application', as: :user_application
  get 'profile' => 'users#profile', as: :user_profile
  put 'profile' => 'users#update', as: :update_user_profile

  get 'users' => 'users#index', as: :users

end

app/models/major.rb
class Major < ActiveRecord::Base
end

app/models/university.rb
class University < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  after_create :init, :mailchimp_subscribe

  has_one :user_info

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.edu+\z/i

  validates :email,   presence: true,
                      length: { maximum: 50 },
                      uniqueness: { case_sensitive: false }
  validates_format_of :email, with: EMAIL_REGEX, message: "You must have a valid .edu email address."

  def greeting
    first_name = self.user_info.first_name
    first_name.blank? ? self.email : first_name
  end

  def status
    self.admitted? ? "accepted" : "pending"
  end

  def major
    self.user_info.major
  end

  def university
    self.user_info.university
  end

  def find_university
    # grab domain from email address
    school_url = self.email.split("@")[1]
    # grab first result
    university = University.where("url LIKE ?", "%#{school_url}%")[0]
    return university.try(:name)
  end

  def mailchimp_subscribe
    # subscribe them to the new "registered" Hackpoly 2015 mailchimp list
    list_id = ENV['MAILCHIMP_LIST_ID']
    MAILCHIMP.lists.delay.subscribe(list_id,
                              { email: self.email },
                              { 'FNAME' => '', 'LNAME' => '' },
                              'html', false)
  end

  def init
    # initialize user_info, prefill university field from email
    UserInfo.create(user: self, university: self.find_university) if self.user_info.nil?
  end


end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base

  belongs_to :user

  validates :first_name,          length: { maximum: 100 }
  validates :last_name,           length: { maximum: 100 }
  validates :major,               length: { maximum: 100 }
  validates :website_url,         length: { maximum: 100 }
  validates :github_url,          length: { maximum: 100 }
  validates :linkedin_url,        length: { maximum: 100 }
  validates :coolest_built,       length: { maximum: 300 }
  validates :previous_hackathons, length: { maximum: 300 }
  validates :university,          length: { maximum: 100 }
  validates :year_in_school,      length: { maximum: 10 }
  validates :skillset,            length: { maximum: 20 }

  # user stats
  validates :gender,              length: { maximum: 30 }
  validates :age,                 length: { maximum: 2 },
                                  numericality: { greater_than: 0,
                                                  allow_nil: true }
  validates :ethnicity,           length: { maximum: 50 }

  def self.year_in_school_choices
    ["Freshman", "Sophomore", "Junior", "Senior", "Graduate Student"]
  end

  def self.skillset_choices
    ["Hacker", "Designer", "Marketer", "I'm just awesome"]
  end

  def self.gender_choices
    ["Male", "Female", "Other", "Prefer not to disclose"]
  end

  def self.ethnicity_choices
    ["Hispanic or Latino", "American Indian or Alaska Native", "Asian", "Black or African American", "Native Hawaiian or Pacific Islander", "White", "Other", "Two or more ethnicities", "Prefer not to disclose"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Devise
  def after_sign_in_path_for(resource)
    # go to profile after signing in if it is first time logging in
    if current_user.sign_in_count == 1
      user_profile_path
    else
      user_application_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def hackweek
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

protected

def after_update_path_for(resource)
  user_application_path
end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin, only: [:index]

  def application
    @user = current_user
  end

  def profile
    @user = current_user
    @user_info = @user.user_info
    @majors = Major.pluck(:name)
    @universities = University.pluck(:name)
  end

  def update
    @user = current_user
    @user_info = @user.user_info
    @majors = Major.pluck(:name)
    if current_user.user_info.update(user_info_params)
      flash[:success] = "Your profile has been updated!"
      redirect_to update_user_profile_path
    else
      render 'profile'
    end
  end

  def index
    @emails = MAILCHIMP.lists.members(ENV['MAILCHIMP_LIST_ID'])['data']
  end

private

def user_info_params
  params.require(:user_info).permit(:first_name, :last_name, :major, :year_in_school, :skillset, :website_url, :github_url, :linkedin_url, :previous_hackathons, :coolest_built, :university, :age, :gender, :ethnicity)
end

def authorize_admin
  if current_user.admin?
    return
  else
    redirect_to root_url
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.haml
.flash-messages-container.container
  %br/
  - flash.each do |key, value|
    .row
      .flash-message.col-sm-12.text-center
        %h4= value

app/views/layouts/_footer.html.haml
.footer
  .container
    .row
      .col-xs-12.col-sm-6.text-left
        %p
          %a{:href => "https://github.com/teamhackpoly", target: "_blank"}
            Site
          by
          %a{:href => "http://twitter.com/BryanTbury", target: "_blank"} Bryan Thornbury
          and
          %a{:href => "http://twitter.com/austinlchang", target: "_blank"} Austin Chang
        %br
        %p
          Questions, comments, concerns? Reach us at
          = link_to "info@hackpoly.com", "mailto:info@hackpoly.com"
      .col-xs-12.col-sm-6.text-right
        %small Organized By
        %br/
        %a{:href => "http://polyfounders.com"}
        = link_to "http://polyfounders.com", target: "_blank" do
          = image_tag "clubs/poly_founders.png", alt: "Hackpoly Hosted by Poly Founders", id: "pf-logo"
    %br/
%script{:src => "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"}
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','http://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46285917-1', 'hackpoly.com');
  ga('send', 'pageview');

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title hackpoly | hack the future
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / External Stylesheets
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.0/lumen/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway:200,600|Oswald:400,700", :rel => "stylesheet", :type => "text/css"}/
    // Favicon
    %link{:href => "/apple-touch-icon-57x57.png", :rel => "apple-touch-icon", :sizes => "57x57"}/
    %link{:href => "/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
    %link{:href => "/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "/apple-touch-icon-60x60.png", :rel => "apple-touch-icon", :sizes => "60x60"}/
    %link{:href => "/apple-touch-icon-120x120.png", :rel => "apple-touch-icon", :sizes => "120x120"}/
    %link{:href => "/apple-touch-icon-76x76.png", :rel => "apple-touch-icon", :sizes => "76x76"}/
    %link{:href => "/favicon-96x96.png", :rel => "icon", :sizes => "96x96", :type => "image/png"}/
    %link{:href => "/favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
    %link{:href => "/favicon-32x32.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
    %meta{:content => "#2d89ef", :name => "msapplication-TileColor"}/

    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top.animated-nav{:role => "navigation"}
      .container
        .row.no-margin
          .hidden-xs.col-sm-2.text-left.navmodule
            %a{:href => "http://facebook.com/hackpoly", target: "_blank"}
              %i.fb-link.fa.fa-facebook-square
            %a{:href => "http://twitter.com/hackpoly", target: "_blank"}
              %span.twitter-link.fa.fa-twitter-square
          .visible-xs-block.col-xs-2.text-left.navmodule
            %button#sidebar-toggle.btn{"data-toggle" => "offcanvas"}
              %i.fa.fa-bars
          .col-xs-8.col-sm-8.text-center
            .navbar-logo
              = link_to root_path do
                = image_tag 'hackpoly.png', alt: "cal poly pomona hackathon logo", id: "hpoly-logo"
          .hidden-xs.col-sm-2.text-right.navmodule
            - if user_signed_in?
              = link_to "Application", user_application_path, class: "btn btn-primary"
            - else
              = link_to "Apply", new_user_registration_path, class: "btn btn-primary"

    .app-container
      .container-bg.subtle
        .container-fluid
          = yield
          - if !current_page?(root_path)
            %br/
            = render partial: "layouts/footer"

app/views/pages/hackweek.html.haml
/ All Main Content Here
= render partial: 'shared/page_nav'
.hackweek-page.container
  .col-xs-12.no-padding.no-margin
    #header.row
      .hero-line.col-xs-12
        %p.pre-hero Hackpoly Presents
        %h1 Hack Week
        %p.post-hero Prepare for Hackpoly 2015 by learning from the pros.
    #content.row
      #android.hack-session.col-xs-12.col-sm-6
        %h2 Android
        %p.date February 16th 6PM - 8PM
        %p.location Cal Poly Pomona
        %p.description Come learn the basics of making Android apps. Bring your laptop and run your first app in 2 hours.
        %br/
        %a.btn.btn-default{:href => "https://hackweekandroid.eventbrite.com", target: "_blank"} Register Now
      #git.hack-session.col-xs-12.col-sm-6
        %h2 Git
        %p.date February 17th 6PM - 8PM
        %p.location Cal Poly Pomona
        %p.description Version Control (such as Git) can offer powerful capabilities to teams of software developers. However, without enough experience, things can quickly go awry. Learn how to take full advantage of Git.
        %br/
        %a.btn.btn-default{:href => "https://hackweekgit.eventbrite.com", target: "_blank"} Register Now
      #web.hack-session.col-xs-12.col-sm-6
        %h2 Web Backend
        %p.date February 18th 6PM - 8PM
        %p.location Cal Poly Pomona
        %p.description Most websites are more than just simple HTML. Come learn to build a powerful backend running on a server and using a database.
        %br/
        %a.btn.btn-default{:href => "http://hackweekwebbackend.eventbrite.com", target: "_blank"} Register Now
      #design.hack-session.col-xs-12.col-sm-6
        %h2 UI/UX & Design
        %p.date February 19th 6PM
        %p.location Cal Poly Pomona
        %p.description Come learn the basics of creating a great user experience through design.
        %br/
        %a.btn.btn-default{:href => "http://hackweekdesign.eventbrite.com", target: "_blank"} Register Now

app/views/pages/index.html.haml
.row.row-offcanvas.row-offcanvas-left.no-margin
  / Sidebar Content
  #sidebar.col-xs-6.visible-xs-block.sidebar-offcanvas
    %ul.list
      %li
        %a{:href => "http://facebook.com/hackpoly", target: "_blank"}
          %i.share-link.fa.fa-facebook-square
          %span.share-text Facebook
      %li
        %a{:href => "http://twitter.com/hackpoly", target: "_blank"}
          %i.share-link.fa.fa-twitter-square
          %span.share-text Twitter
      %li
        %a{:href => "http://github.com/teamhackpoly", target: "_blank"}
          %i.share-link.fa.fa-github-square
          %span.share-text Source Code
      %li
        - if user_signed_in?
          = link_to "Application", user_application_path, class: "btn btn-primary sidebar-button"
        - else
          = link_to "Apply", new_user_registration_path, class: "btn btn-primary sidebar-button"
  / All Main Content Here
  .col-xs-12.no-padding
    / Header Portion
    #top-image.image-module
      .container
        / Prenav
        #prenav.row.no-margin
          .hidden-xs.col-sm-2.text-left.navmodule
            %a{:href => "http://facebook.com/hackpoly", target: "_blank"}
              %i.fb-link.fa.fa-facebook-square
            %a{:href => "http://twitter.com/hackpoly", target: "_blank"}
              %span.twitter-link.fa.fa-twitter-square
            %a{:href => "http://instagram.com/hackpoly", target: "_blank"}
              %span.instagram-link.fa.fa-instagram-square
          .visible-xs-block.col-xs-2.text-left.navmodule
            %button#sidebar-toggle.btn{"data-toggle" => "offcanvas"}
              %i.fa.fa-bars
          .col-xs-8.col-sm-8.text-center
            .navbar-logo
              = image_tag "hackpoly-white.png", alt: "cal poly pomona hackathon logo", id: "hpoly-logo-white"
      .hero-line
        %h1
          Hack the Future
          %span.hidden-xs in SoCal
        .action
          #application-form
          = link_to "Apply", user_signed_in? ? user_application_path : new_user_registration_path, id: "apply-button", class: "btn btn-primary"
    .subtle
      .container
        #information.module
          %h2.title-line
            %span
              %span.hidden-xs Hackpoly is Cal Poly Pomona's Annual Hackathon
              %span.visible-xs-inline CPP's Hackathon.
          .row.text-center
            .col-xs-12.col-sm-6.col-md-6.col-lg-6
              %a.font-large{:href => "http://maps.google.com/maps/api/staticmap?center=34.052142,-117.814411&zoom=13&markers=Cal+Poly+Pomona+3801+West+Temple+Avenue+Pomona,+CA+91768&path=color:0x0000FF80|weight:5|34.06061,-117.81652&size=500x300&sensor=TRUE_OR_FALSE", target: "_blank"}
                Cal Poly Pomona
                %br/
                Southern California
              %h4 WHERE
            .col-xs-12.col-sm-6.col-md-6.col-lg-6
              %a.font-large{:href => "https://www.google.com/calendar/event?action=TEMPLATE&tmeid=MHQzcWpjN3Y2ZDN2YTlpYWZzM2E5dGc0bXMgcWYxbHNlNXQwMjllaDdxMXQ3MWVwbWdqdDRAZw&tmsrc=qf1lse5t029eh7q1t71epmgjt4%40group.calendar.google.com", target: "_blank"}
                Friday, Feb 20th 6 PM -
                %br/
                Saturday, Feb 21st 10 PM
              %h4 WHEN
        #faq.module
          %h2.title-line
            %span FAQ
          .row.text-justify
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                What is a hackathon?
              %p.answer
                A hackathon is difficult to explain. It's a type of invention competition at its core. Here is a hackathon in a nutshell: Form a team, come up with an idea, work tirelessly for 24 hours to bring this idea to reality, demo what was built, and win some awesome prizes.
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                Do I need to know how to code?
              %p.answer
                Knowing how to code will definitely help, but isn't a requirement. Graphic design can be a large aspect of some projects. We will be hosting a series of workshops about apps, websites, and more in the week preceding Hackpoly.
                = link_to 'Check out Hack Week!', hackweek_path
            .clearfix.visible-sm-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                What should I bring?
              %p.answer
                Use your best judgement of course, but these are some things we recommend:
              %ul
                %li A computer to work on (even a desktop will work)
                %li Toothbrush and Toothpaste
                %li Extra clothes
                %li Sleeping bag and a pillow (if you want to sleep)
                %li Any hardware that you'll need (arduinos, raspberry pi, etc... )
            .clearfix.visible-md-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                How long is the event?
              %p.answer
                The entire event (registration to judging) will run about 26 hours. A final schedule will be released closer to the event.
            .clearfix.visible-sm-block
            .clearfix.visible-lg-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                What kind of stuff should I build? Is there a theme?
              %p.answer
                Hackpoly doesn't have a theme and you can build whatever you like. At Hackpoly 2014,
                projects ranged from
                = succeed "," do
                  %a{:href => "https://flic.kr/p/jycAPA", target: "_blank"} a hacked car
                to an
                = succeed "," do
                  %a{:href => "https://flic.kr/p/jyHcUP", target: "_blank"} electric cello
                to an app that helps track your pantry.
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                Do I need a team?
              %p.answer
                You can put together a team beforehand, or join one during the event. Many people come with an idea and try to build a team around it. Others come in with a team and a set idea.
            .clearfix.visible-sm-block
            .clearfix.visible-md-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                How much does it cost?
              %p.answer
                Hackpoly is free for all attendees.
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                Do I need to be a student?
              %p.answer
                Yes. In order to attend Hackpoly, you must have a valid .edu email address and can't have graduated more than 6 months prior.
            .clearfix.visible-sm-block
            .clearfix.visible-lg-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                Will there be food?
              %p.answer
                We will be providing meals, drinks, and snacks. Don't worry, you won't be going hungry.
            .clearfix.visible-md-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                Do I own my project after the event?
              %p.answer
                Don't worry, your team will own the project. We want to see the awesome stuff you can make, but even more than that we want to see your project take off afterward.
            .clearfix.visible-sm-block
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                How will projects be judged?
              %p.answer
                You will demo your project to a panel of judges, then they will make decisions based on a combination of novelty, utility, design, overall coolness, and technical complexity.
            .col-xs-12.col-sm-6.col-md-4.col-lg-3
              %p.question
                This sounds awesome, what do I do now?
              %p.answer
                Look in the nav bar at the top of the page, and press the apply button! Don't be intimidated if this is your first hackathon, we want to see you here.
            .clearfix.visible-sm-block
            .clearfix.visible-md-block
            .clearfix.visible-lg-block
        / End of FAQ Section
        #sponsors.module
          %h2.title-line
            %span Sponsors
          .block.platinum
          .block.gold
          .block.silver
            = link_to "http://mlh.io", target: "_blank" do
              = image_tag "sponsors/mlh.png", alt: "Major League Hacking sponsors Hackpoly 2015", id: "mlh", class: "grayscale", title: "Hackpoly part of the MLH.io Spring 2015 Lineup"
            = link_to "http://generalassemb.ly", target: "_blank" do
              = image_tag "sponsors/ga.png", alt: "Hackpoly sponsored by General Assembly", id: "generalassembly", class: "grayscale", title: "Hackpoly sponsored by General Assembly"
            .block.bronze
            = link_to "http://food2fork.com", target: "_blank" do
              = image_tag "sponsors/food2fork.png", alt: "Food2Fork sponsors Hackpoly 2015", id: "food2fork", class: "grayscale", title: "Food2Fork Sponsors Hackpoly"
            = link_to "http://jetbrains.com", target: "_blank" do
              = image_tag "sponsors/jetbrains.png", alt: "Jetbrains sponsors Hackpoly 2015", id: "jetbrains", class: "grayscale", title: "Jetbrains Sponsors Hackpoly"
    = render partial: "layouts/footer"
  / Internal Behavior
  :javascript
    $(document).ready(function(){
      //When scrolling past the header text, bring in navbar
      var $button = $("#apply-button").first();
      var $nav = $(".navbar").first();
      var $prenav = $("#prenav").first();

      //For animating the navbar
      var oldHeight = $nav.height();
      var navVis = false;

      $(window).scroll(function(){
        if($(document).scrollTop() > ($button.position().top)){
          if(!navVis){

           navVis = true;
           $nav.addClass('notransition');
           $nav.css('height',"20px");
           console.log($nav.css('height'));
           $nav.removeClass('notransition');

           $nav.css('display','block');
           $nav.css('height',oldHeight);
           $nav.css('opacity',1);

          }
        }

        if($(document).scrollTop() <= 5 && navVis){
          $nav.css('height',"0px");
          $nav.css('opacity',0);

          //Timeout synced with css animation
          setTimeout(function(){
            if(navVis){
              $nav.addClass('notransition');
              $nav.css('display','none');
              $nav.css('height',oldHeight);
              $nav.removeClass('notransition');

              navVis = false;
            }
          }, 500);
        }
      });

      //Mobile Menu Button Behavior
      $('[data-toggle="offcanvas"]').click(function(){
          $('.row-offcanvas').toggleClass('active');
      });
    });

app/views/shared/_page_nav.html.haml
%nav.navbar.navbar-default.no-margin{:role => "navigation"}
  .container
    .row
      .col-xs-3.text-left.navmodule
        %a{:href => "http://facebook.com/hackpoly", target: "_blank"}
          %i.fb-link.fa.fa-facebook-square
        %a{:href => "http://twitter.com/hackpoly", target: "_blank"}
          %span.twitter-link.fa.fa-twitter-square
        %a{:href => "http://instagram.com/hackpoly", target: "_blank"}
          %span.instagram-link.fa.fa-instagram-square
      .col-xs-6.text-center
        .navbar-logo
          = link_to root_path do
            = image_tag 'hackpoly.png', alt: 'cal poly pomona hackathon logo', id: 'hpoly-logo'
      .col-xs-3.text-right.navmodule
        - if user_signed_in?
          .hidden-xs
            = link_to "Application", user_application_path, class: "btn btn-primary"
          .visible-xs
            = link_to user_application_path, class: "btn btn-primary" do
              %i.fa.fa-user
        - else
          = link_to "Apply", new_user_registration_path, class: "btn btn-primary"
= render partial: 'layouts/flash_messages'

app/views/users/application.html.haml
= render partial: "shared/page_nav"
.application-page.container
  .row
    .greeting.col-md-12.text-center
      %h1= "HELLO, #{@user.greeting.upcase}!"
  .row
    .app-status.col-md-12.text-center
      %h4
        - if current_user.admitted?
          = "Congratulations! Your application has been <span class='user-status'>#{current_user.status}</span> for Hackpoly 2015. Please check your email regularly for further instructions.".upcase
        - else
          = "Your application is currently <span class='user-status'>#{current_user.status}</span>. Please check back regularly for any updates to your application status.".html_safe
  .row
    .app-page-links.col-md-6.col-md-offset-3.col-sm-8.col-sm-offset-2.col-xs-12.text-center
      %ul.list-unstyled
        .hidden-xs.s10
        %li.text-uppercase
          = link_to 'edit my profile', user_profile_path, class: "btn btn-primary btn-block"
        .hidden-xs.s10
        %li.text-uppercase
          = link_to 'account settings', edit_user_registration_path, class: "btn btn-primary btn-block"
        .hidden-xs.s10
        %li.text-uppercase
          = link_to 'logout', destroy_user_session_path, method: :delete, class: "btn btn-primary btn-block"

app/views/users/index.html.haml
%table.table.table-striped.table-bordered
  %th
    Last Name
  %th
    First Name
  %th
    Email
  %th
    List
  %th
    Status
  - @emails.each do |e|
    %tr
      %td
        = e['merges']['LNAME']
      %td
        = e['merges']['FNAME']
      %td
        = e['merges']['EMAIL']
      %td
        = e['list_name']
      %td
        = e['status']

app/views/users/reset_password_instructions.html.haml
%a.mcnButton{:href => edit_password_url(@resource, reset_password_token: @token), :style => "font-weight: bold;letter-spacing: normal;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;", :target => "_blank", :title => "Reset Password"} Reset Password